### ISSUE TITLE
Default smv_released_pattern doesn't work because refname includes "refs/" prefix

### ISSUE THREAD

**Issue by jli** [sphinx-contrib/multiversion#59]
The default `smv_released_pattern` is `r"^tags/.*$"`. However, I noticed that none of my tags had `is_released` set on them properly.

I added debug printing, and it seems that `gitref.refname` on [this line](https://github.com/Holzhaus/sphinx-multiversion/blob/d079a9b50154e8cbec081050a0612edecafe1f46/sphinx_multiversion/main.py#L280) includes the `refs/` prefix, which explains why the released pattern doesn't match. I verified this by setting `smv_released_pattern` to `r"^refs/tags/.*$"`.

**Comment by proc-2** [comment]
Also, because it uses `re.match`, using `^` is irrelevant. Should it use `re.search` instead?
