### ISSUE TITLE
'smv_released_pattern' examples should start with 'refs/'

### ISSUE THREAD

**Issue by LewisGaul** [sphinx-contrib/multiversion#66]
The example regex patterns for `smv_released_pattern` start with `^tags/`, `^heads/` and `^remotes/`, however this appears to be missing the required `refs/` at the start. I was seeing everything failing to match until I made it `^refs/tags/.*$`.

See https://holzhaus.github.io/sphinx-multiversion/master/configuration.html.

Thanks for the tool :)

**Comment by tonywhittam** [comment]
Thanks @LewisGaul. I was having this issue and confirm that it works exactly the way you said.

**Comment by BurningEnlightenment** [comment]
Duplicate of #59
