### ISSUE TITLE
Cannot make sphinx-multiversion work when using nbsphinx

### ISSUE THREAD

**Issue by ocefpaf** [sphinx-contrib/multiversion#87]
First of all, thanks for this awesome package! Works great!!

I have a few setups where I use the nbsphinx extension but when I call sphinx-multiversion the notebooks are ignored. Not sure if I'm doing something wrong or if sphinx-multiversion is not designed to work with other sphinx extensions.

**Comment by BurningEnlightenment** [comment]
Hi, can you provide us with a reprex (reproducing example) or if possible a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by ocefpaf** [comment]
Sorry, I moved to another setup 2 years ago and I don't even remember what I had before. Thank you for taking a look at this issue! I'll probably try `multiversion` if I have to set a new project up at some point.

**Comment by BurningEnlightenment** [comment]
Oh, no problem. Thanks for the quick response!
