### ISSUE TITLE
Consider moving to sphinx-contrib and appointing a second maintainer

### ISSUE THREAD

**Issue by BurningEnlightenment** [sphinx-contrib/multiversion#88]
@Holzhaus it seems like you are currently occupied with other projects and while that's perfectly fine, it would be unfortunate if this awesome sphinx extension would be strangled by it.

Therefore I propose to appoint one or two willing past contributors as maintainers and to move the repository to the [sphinx-contrib] organization. What is your opinion on this?

[sphinx-contrib]: https://github.com/sphinx-contrib/github-administration

**Comment by jykae** [comment]
Also a bit worried about maintenance of this great project. Hopefully this sorts out ❤️

**Comment by real-yfprojects** [comment]
Since this projects seems to be unmaintained, I created [sphinx-polyversion](https://github.com/real-yfprojects/sphinx-polyversion) *(such an original name, if have a better idea pls tell me)*. I hope this helps people looking for a tool to build multiple versions of their docs.

**Comment by d33bs** [comment]
Just a bump here to mention a kudos to the original development efforts by @Holzhaus and others who helped create this project! It really says something that this still works relatively well ~4 years after the latest release.

That said, to keep the project maintained it's clear there's a need to add maintainers or move the project to [sphinx-contrib](https://github.com/sphinx-contrib/github-administration) as @BurningEnlightenment suggested. @Holzhaus please don't hesitate to let the community know of your thoughts as well on this and thank you for creating the project.

**Comment by tjex** [comment]
Agreed. Things shouldn't rot! Some much work has been done, and many blog posts / tutorials point here. There will always be a lot of drop off if people come here and don't investigate which forks are actually active.

I guess the next best solution would be to update the readme with some community suggestions of successor projects, and just link to them.

**Comment by Holzhaus** [comment]
Hi, sorry for the long silence from my side. I originally created this project for the [Mixxx manual](https://manual.mixxx.org), where it's still actively used. So it still works for me ;-)

Unfortunately, my job and other FOSS projects I'm working on currently don't leave enough free time to maintaining this properly and help other people integrate it in more elaborate sphinx setups than mine.

In the spirit of free software, I appreciate the forks and I have no concerns or anything to move this to sphinx-contrib if someone wants to take over maintenance.

**Comment by d33bs** [comment]
Thanks @Holzhaus ! We appreciate your efforts here and honesty about availability. Given what you mention, maybe outlining some next steps could help. I feel a small group of us could effectively maintain the repository after transferring it to [`sphinx-contrib`](https://github.com/sphinx-contrib) for long-term support.

The following rough steps might be needed to reach this (please don't hesitate to correct / adjust - this is just a start!):

1. Fork the current repo here to a personal account
2. File an issue under `sphinx-contrib/github-administration` asking for organizational access
3. Migrate the fork to `sphinx-contrib`
4. Perform update PR's to update the documentation of the fork under `sphinx-contrib` (making sure to highlight maintainer status and new links / setup new GitHub Pages). We also might need to make adjustments to a `CONTRIBUTING` and `CODE_OF_CONDUCT` to help migrate things.
5. Begin notifying open PR's under this repo via a comment about the new repo and the openness to contribute under `sphinx-contrib`.
6. Make a "migration" PR here making a change to the main readme which notifies others about the new repository under `sphinx-contrib` and the maintenance status of this repo.

Thoughts? I think two or more maintainers for the `sphinx-contrib` fork could make an effective team. @BurningEnlightenment, would you possibly be interested in taking lead as you initially opened this issue? I'd be interested in helping maintain or migrate the project under `sphinx-contrib`.

@jykae @real-yfprojects @tjex (or others who may be watching the issue) - would you also be interested in being involved?

**Comment by BurningEnlightenment** [comment]
> In the spirit of free software, I appreciate the forks and I have no concerns or anything to move this to sphinx-contrib if someone wants to take over maintenance.

@Holzhaus thank you so much for the work put into this project! 🙏 

> Fork the current repo here to a personal account

Ideally, we would move this repository directly to `sphinx-contrib`. The GitHub UI still treats all forks as equal second class citizens wrt defaults (e.g. default PR target repo). We'd need to involve @Holzhaus for this step, though.

> I think two or more maintainers for the sphinx-contrib fork could make an effective team. @BurningEnlightenment, would you possibly be interested in taking lead as you initially opened this issue?

If no other more suitable person steps up, I wouldn't be opposed. I can take care of the "management" aspects for issues, etc. and code reviews. But bear in mind that I'm not nearly as competent with Python as with C++/TypeScript/Haskell/... so don't expect any heroic contributions. However, I do use this at work and can probably divert a small bit of worktime to address critical issues or things like the pyro theme integration which my employer recognizes as benefitial.

If nothing further comes up, I'll open an issue at `sphinx-contrib/github-administration` next Friday. Maybe they have additional suggestions.
