### ISSUE TITLE
Building and publishing different versions separately

### ISSUE THREAD

**Issue by stefanseefeld** [sphinx-contrib/multiversion#95]
The existing documentation explains how to build documentation for multiple versions in a single command.
I find a much more common use-case is to build (and publish) documentation for individual versions separately, then wanting to assemble them into a single "hub" (such as ReadTheDocs) as these new versions become available.

Is such a use-case already supported ? Is it documented and I just haven't found it yet ? 
If not, what would it take to add support for that ?

**Comment by BurningEnlightenment** [comment]
Hi, the use case is not supported at the moment. This runs into the same issues as #63 and it is therefore unlikely that this will ever be implemented.
